import Image from "next/image";

export default function Home() {
  return (
    <>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
      <div>beans</div>
    </>
  );
}
